#!/bin/bash

sudo apt-get update
y | sudo apt-get upgrade
y | sudo apt-get install libatlas-base-dev
y | sudo apt-get install libjasper-dev
y | sudo apt-get install libqtgui4
y | sudo apt-get install python3-pyqt5
y | sudo apt install libqt4-test
sudo pip3 install opencv-python==3.4.6.27
